'use strict';
const assert=require('assert');
const {Simulation}=require('../src/integrity.js');
const {loadBundle}=require('../tools/load-bundle.js');
const bundle=loadBundle('open_arena_short_control.json');
bundle.observation.record_trajectories=false;
bundle.model.movement.angular_sigma_rad_sqrt_s=0;
bundle.model.movement.speed_noise_sigma_sqrt_s=0;
bundle.model.movement.pause_rate_s=0;
bundle.apparatus.entry_points.center.x=296;
bundle.experiment.protocol.entry_state.position_jitter_mm=0;
bundle.experiment.protocol.entry_state.heading_jitter_rad=0;
const sim=new Simulation(bundle,123),a=sim.ants[0];
a.heading=0;a.baseSpeed=10;a.speedFactor=1;a.turnScale=1;
sim.step(.2);
assert.strictEqual(a.outcome,'arena_exit');
assert(Math.abs(a.completedAt-.1)<1e-4,`truth exit ${a.completedAt}`);
const measured=sim.summary().observed_metrics.ants[0];
assert.strictEqual(measured.total_frames,4);
assert(Math.abs(measured.observed_outcome_frame_time_s-.12)<1e-9,`observed frame ${measured.observed_outcome_frame_time_s}`);
assert(Math.abs(measured.time_to_arena_edge_s-.16)<1e-9,`paper-compatible time ${measured.time_to_arena_edge_s}`);
console.log(`boundary-timing.test.js PASS truth=${a.completedAt.toFixed(4)} observed_frame=${measured.observed_outcome_frame_time_s.toFixed(2)} paper_time=${measured.time_to_arena_edge_s.toFixed(2)}`);
