'use strict';
const assert=require('assert'),path=require('path');
const {readJson}=require('../tools/load-bundle.js');
const est=require('../tools/run-h2-estimation.js');
const root=path.resolve(__dirname,'..');
const policy=readJson(path.resolve(root,'hypotheses','h2_parameter_estimation_v1.json'));
const target=readJson(path.resolve(root,'reference','poissonnier2026_h2_estimation_targets.json'));
const cal=readJson(path.resolve(root,'reference','calibration_manifest.json'));
const source=readJson(path.resolve(root,'reference','poissonnier2026_source_manifest.json'));
est.validate(policy,target,cal,source);
assert.strictEqual(cal.datasets.poissonnier2026_open_arena.allowed_for_fitting,false,'canonical fitting must stay locked');
assert.strictEqual(cal.datasets.poissonnier2026_open_arena.allowed_for_development_parameter_estimation,true);
assert.strictEqual(cal.datasets.poissonnier2026_ymaze.allowed_for_development_parameter_estimation,false);
assert.strictEqual(target.rows.length,51);
assert.deepStrictEqual([...new Set(target.rows.map(r=>r.colony))].sort((a,b)=>a-b),[0,7,16,20,21,27]);
for(const c of [0,7,16,20,21,27])assert.deepStrictEqual([...new Set(target.rows.filter(r=>r.colony===c).map(r=>r.path_length))].sort(),['l','s']);
assert(!target.excluded_from_estimation.includes('Total_Frames'));
for(const forbidden of ['Average_Speed_Moving','Traveled_Dist_Moving','Straightness','Prop_time_moving'])assert(target.excluded_from_estimation.includes(forbidden));
const c1=est.candidate(7,policy,false),c2=est.candidate(7,policy,false);assert.deepStrictEqual(c1,c2,'candidate sequence must be deterministic');
assert(c1.rho>0&&c1.rho<1);assert(est.effective(c1,1000)>est.effective(c1,200));
const tampered=JSON.parse(JSON.stringify(cal));tampered.datasets.poissonnier2026_ymaze.allowed_for_development_parameter_estimation=true;assert.throws(()=>est.validate(policy,target,tampered,source),/Y-maze/);
console.log('h2-estimation.test.js PASS '+JSON.stringify({rows:target.rows.length,colonies:6,candidate:c1}));
