'use strict';
const assert=require('assert');
const path=require('path');
const{Simulation}=require('../src/integrity.js');
const{loadBundle,readJson}=require('../tools/load-bundle.js');
const{runH2Mechanism,validateFrozenMechanism}=require('../tools/run-h2-mechanism.js');
const root=path.resolve(__dirname,'..'),modelId='lasius_niger_locomotion_h2_v1';
const freeze=readJson(path.resolve(root,'hypotheses','h2_persistent_directional_state_v1.json'));
const short=loadBundle('open_arena_short_control.json',{modelId}),long=loadBundle('open_arena_long_control.json',{modelId});
validateFrozenMechanism(short.model,freeze);
const s=new Simulation(short,12345),l=new Simulation(long,12345);
const lambda=freeze.parameters.lambda_mm.value,tau=freeze.parameters.tau_s.value;
const expectedShort=1-Math.exp(-200/lambda),expectedLong=1-Math.exp(-1000/lambda);
assert(Math.abs(s.ants[0].directionalPersistenceInitial-expectedShort)<1e-12);
assert(Math.abs(l.ants[0].directionalPersistenceInitial-expectedLong)<1e-12);
assert(l.ants[0].directionalPersistenceInitial>s.ants[0].directionalPersistenceInitial);
for(let i=0;i<50;i++)s.step(.02);
assert(Math.abs(s.ants[0].directionalPersistence-expectedShort*Math.exp(-1/tau))<1e-12,'P must follow exact exponential decay');
const zeroH2=loadBundle('open_arena_short_control.json',{modelId});zeroH2.experiment.protocol.state_facts.recent_constrained_travel_mm=0;
const zeroH0=loadBundle('open_arena_short_control.json');zeroH0.experiment.protocol.state_facts.recent_constrained_travel_mm=0;
const zh2=new Simulation(zeroH2,777),zh0=new Simulation(zeroH0,777);for(let i=0;i<200;i++){zh2.step(.02);zh0.step(.02);}assert.strictEqual(zh2.ants[0].x,zh0.ants[0].x);assert.strictEqual(zh2.ants[0].y,zh0.ants[0].y);assert.strictEqual(zh2.ants[0].heading,zh0.ants[0].heading);assert.strictEqual(zh2.ants[0].distanceTravelled,zh0.ants[0].distanceTravelled);
const injected=loadBundle('open_arena_short_control.json',{modelId});injected.experiment.protocol.state_facts.directional_persistence=.9;assert.throws(()=>new Simulation(injected,1),/(Latent biological state forbidden|Model parameter forbidden|Biology override forbidden)/);
const protocolInjected=loadBundle('open_arena_short_control.json',{modelId});protocolInjected.experiment.protocol.directional_persistence={decay:{tau_s:999}};assert.throws(()=>new Simulation(protocolInjected,1),/Biology override forbidden/,'H2 biology must be forbidden anywhere in assay protocol, not only state_facts');
const tauInjected=loadBundle('open_arena_short_control.json',{modelId});tauInjected.experiment.protocol.analysis_note={tau_s:999};assert.throws(()=>new Simulation(tauInjected,1),/Biology override forbidden/,'H2 parameter names must not be legal assay-side overrides');
const report=runH2Mechanism({trials:12,firstSeed:810000,dt:.02});assert.strictEqual(report.fit_performed,false);assert.strictEqual(report.reference_targets_accessed,false);assert.strictEqual(report.ymaze_accessed,false);assert.strictEqual(report.selection_performed,false);assert(report.initial_latent_state.long.p0>report.initial_latent_state.short.p0);assert.strictEqual(report.model_id,modelId);
console.log('h2-persistence.test.js PASS '+JSON.stringify({p0_short:expectedShort,p0_long:expectedLong,model_hash:report.model_hash}));
