'use strict';
const assert=require('assert');
const {MeasurementPipeline,interpolateFrame}=require('../src/measurement.js');
const obs={id:'test',fps:25,record_trajectories:false,tracking:{movement_classifier:{type:'frame_displacement_threshold',threshold_mm:0,status:'test'}},metric_definitions:{central_zone_fraction:{type:'horizontal_band',center_y_mm:105,half_width_mm:10}}};
const exp={requested_metrics:['central_zone_fraction','mean_moving_speed','total_distance','time_to_arena_edge','path_straightness','exit_coordinate']};
const p=new MeasurementPipeline(obs,exp,{});
p.observe({time_s:0,ants:[{id:0,x:0,y:105,outcome:null}]});p.observe({time_s:.04,ants:[{id:0,x:1,y:105,outcome:null}]});p.observe({time_s:.08,ants:[{id:0,x:3,y:120,outcome:'arena_exit'}]});
const s=p.summary([{id:0,finished:true,outcome:'arena_exit',completedAt:.073,exitX:3,exitY:120,x:3,y:120}]),r=s.ants[0];
assert(Math.abs(r.central_zone_fraction-.5)<1e-9,r.central_zone_fraction);const d=1+Math.hypot(2,15);assert(Math.abs(r.total_distance_mm-d)<1e-9);assert(Math.abs(r.mean_moving_speed_mm_s-d/.08)<1e-9);assert.strictEqual(r.time_to_arena_edge_s,.08);
const before=[{id:0,x:0,y:0,heading:0,state:'moving',outcome:null,finished:false,completedAt:null}],after=[{id:0,x:10,y:0,heading:Math.PI/2,state:'moving',outcome:null,finished:false,completedAt:null}],f=interpolateFrame(before,after,0,.05,.04,obs,null);assert(Math.abs(f.ants[0].x-8)<1e-9,f.ants[0].x);assert.strictEqual(f.time_s,.04);console.log('measurement.test.js PASS');
