'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path');
const {execFileSync}=require('child_process');
const root=path.resolve(__dirname,'..');
const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const blob=p=>execFileSync('git',['hash-object',p],{cwd:root,encoding:'utf8'}).trim();
const p=read('hypotheses/p1_reachability_execution_v1.json');
assert.strictEqual(blob('hypotheses/p1_reachability_execution_v1.json'),'282a95ec6761acd8d94163b25f712f191181f2ff');
assert.strictEqual(p.id,'P1_reference_free_reachability_execution_v1');
assert.strictEqual(p.status,'execution_policy_frozen_before_P1_runtime_execution');
assert.strictEqual(p.mechanism_freeze.git_blob_sha,'90e86bce29bf45c6e390f7046a6c25a74f409c78');
assert.strictEqual(p.reference_firewall.poissonnier2026_pheromone_response_targets_may_be_loaded,false);
assert.strictEqual(p.reference_firewall.any_reference_outcomes_may_be_loaded,false);
assert.strictEqual(p.reference_firewall.ymaze_may_be_loaded,false);
assert.strictEqual(p.reference_firewall.fit_or_parameter_search,false);
assert.strictEqual(p.reference_firewall.candidate_ranking,false);
assert.strictEqual(p.reference_firewall.adaptive_rerun_or_engineering_value_tuning,false);
assert.strictEqual(p.frozen_execution.physics_dt_s,.02);
assert.deepStrictEqual(p.frozen_execution.engineering_values,{sigma_field_mm:8,kappa_trail_per_s:4,sensor_forward_offset_mm:2,sensor_lateral_half_separation_mm:1.5,nominal_dose_ratio_A:1});
assert.strictEqual(p.frozen_execution.exact_identity_panel.seeds.length,32);
assert.strictEqual(p.frozen_execution.exact_identity_panel.seeds[0],1333001);
assert.strictEqual(p.frozen_execution.exact_identity_panel.seeds[31],1333032);
assert.strictEqual(p.frozen_execution.exact_identity_panel.fixed_time_s,2);
assert.strictEqual(p.frozen_execution.attraction_panel.trials_per_condition,400);
assert.strictEqual(p.frozen_execution.attraction_panel.first_seed,1334001);
assert.strictEqual(p.frozen_execution.attraction_panel.last_seed,1334400);
assert.strictEqual(p.frozen_execution.attraction_panel.common_random_numbers,true);
assert.strictEqual(p.frozen_execution.attraction_panel.zero_dose_ratio_A,0);
assert.strictEqual(p.frozen_execution.attraction_panel.pheromone_dose_ratio_A,1);
assert.match(p.pass_fail_rule.attraction,/strictly greater mean central_zone_fraction AND strictly greater trail_axis_exit_rate/);
assert.match(p.failure_rule,/may not be tuned/);
const runner=fs.readFileSync(path.join(root,'tools/run-p1-reachability.js'),'utf8');
assert.ok(!runner.includes('poissonnier2026_pheromone_response_targets.json'),'reachability runner must not name/load P1 response target');
assert.ok(!/(?:loadBundle|readJson|require)\s*\([^\n)]*y[_-]?maze/i.test(runner),'reachability runner must not load or require Y-maze content');
assert.ok(!/run-p1-estimation|halton|candidate[s]?_per_fold|objective_weight|adaptiveRefinement|localOptimizer/i.test(runner),'reachability runner must not contain estimator/search machinery');
console.log('p1-reachability-policy.test.js PASS');
