'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path');
const {execFileSync}=require('child_process');
const root=path.resolve(__dirname,'..');
const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const blob=p=>execFileSync('git',['hash-object',p],{cwd:root,encoding:'utf8'}).trim();

const rel='hypotheses/p4_highres_execution_precondition_v1.json';
const p=read(rel);
assert.strictEqual(blob(rel),'313f2892a5627195b1319911a87cdfe7884337ae');
assert.strictEqual(p.id,'P4_high_resolution_execution_precondition_v1');
assert.strictEqual(p.status,'authorization_merged_and_permanent_main_ci_green_before_official_execution');
assert.strictEqual(p.authorization_pr_number,41);
assert.strictEqual(p.authorization_main_commit,'c5f8f2c7e8e9efbbe5393777aeada695a712a05b');
assert.strictEqual(p.authorization_git_blob_sha,'d8088ab94480faf0f5db012ca538bdc4d5a42ccb');
assert.strictEqual(p.policy_git_blob_sha,'2d0bdfaba74ad08f8424870f37a48399428ae8b7');
assert.strictEqual(p.estimator_implementation_authorization_git_blob_sha,'e8f26731412d8693a5596da4374de932745b9392');
assert.strictEqual(p.estimator_git_blob_sha,'e57b554c0ad56a0034f4f79ec8090d3e863e3d11');
assert.strictEqual(p.estimator_core_git_blob_sha,'4d985cd7258fc26eb06be75f09bdac4b92325ff0');
assert.strictEqual(p.qualification_report_git_blob_sha,'33cf1216ade03b0f25ddf643cdc28fd5c3df0010');
assert.strictEqual(p.browser_firewall_report_git_blob_sha,'8ae7c0f8940502c64e720b5abafde4fc094a255c');
assert.strictEqual(p.qualification_result_freeze_git_blob_sha,'635b64ff1bfe08f6f914e5fd8bef8306ee0b27d5');
assert.strictEqual(p.response_target_git_blob_sha,'81910c5bd3ec7b1f7728c2c9f100b0e8a6db29ed');
assert.strictEqual(p.execution_workflow_file,'.github/workflows/p4-v034g-official-highres.yml');
assert.strictEqual(p.execution_workflow_git_blob_sha,'1b34c35246117ad483c25c10601c8971fe6f273e');
assert.strictEqual(blob(p.execution_workflow_file),p.execution_workflow_git_blob_sha);
assert.strictEqual(blob('hypotheses/p4_highres_authorization_v1.json'),p.authorization_git_blob_sha);
assert.strictEqual(blob('hypotheses/p4_response_estimation_v1.json'),p.policy_git_blob_sha);
assert.strictEqual(blob('hypotheses/p4_estimator_implementation_authorization_v1.json'),p.estimator_implementation_authorization_git_blob_sha);
assert.strictEqual(blob('tools/run-p4-estimation.js'),p.estimator_git_blob_sha);
assert.strictEqual(blob('tools/p4-estimation-core.js'),p.estimator_core_git_blob_sha);
assert.strictEqual(blob('reports/p4_estimator_qualification_v1.json'),p.qualification_report_git_blob_sha);
assert.strictEqual(blob('reports/p4_estimator_browser_audit_v1.json'),p.browser_firewall_report_git_blob_sha);
assert.strictEqual(blob('hypotheses/p4_estimator_qualification_result_freeze_v1.json'),p.qualification_result_freeze_git_blob_sha);
assert.strictEqual(blob('reference/poissonnier2026_pheromone_response_targets.json'),p.response_target_git_blob_sha);

assert.strictEqual(p.permanent_main_workflow.main_commit,'c5f8f2c7e8e9efbbe5393777aeada695a712a05b');
assert.strictEqual(p.permanent_main_workflow.run_id,34568453092);
assert.strictEqual(p.permanent_main_workflow.run_number,161);
assert.strictEqual(p.permanent_main_workflow.conclusion,'success');
assert.strictEqual(p.permanent_main_workflow.test_job_id,103165280046);
assert.strictEqual(p.permanent_main_workflow.test_job_conclusion,'success');
assert.strictEqual(p.permanent_main_workflow.deploy_job_id,103165436328);
assert.strictEqual(p.permanent_main_workflow.deploy_job_conclusion,'success');

assert.strictEqual(p.official_execution_still_unrun_at_freeze,true);
assert.strictEqual(p.authorized_command_exact,'node tools/run-p4-estimation.js --mode highres --out reports/p4_response_estimation_2000x60_v1.json');
assert.deepStrictEqual(p.cli_parameter_overrides,[]);
assert.strictEqual(p.official_output_artifact_name,'p4-v034g-official-highres');
assert.strictEqual(p.official_report_filename,'p4_response_estimation_2000x60_v1.json');
assert.strictEqual(p.official_provenance_filename,'p4_response_estimation_execution_provenance_v1.json');

const c=p.execution_contract;
assert.strictEqual(c.folds,6);
assert.deepStrictEqual(c.colonies,[0,7,16,20,21,27]);
assert.strictEqual(c.P4_candidates_per_fold_total,2000);
assert.strictEqual(c.positive_P4_halton_candidates,1999);
assert.strictEqual(c.exact_canonical_null_candidates,1);
assert.strictEqual(c.ungated_P3_structural_benchmark_candidates_per_fold_total,2000);
assert.strictEqual(c.ungated_P3_structural_benchmark_positive_candidates,1999);
assert.strictEqual(c.training_trials_per_treatment_path_per_candidate,60);
assert.strictEqual(c.heldout_evaluation_trials_per_treatment_path,120);
assert.strictEqual(c.root_fit_seed,8210000);
assert.strictEqual(c.root_evaluation_seed,8810000);
assert.strictEqual(c.final_all_data_training_trials_per_treatment_path_per_candidate,120);
assert.strictEqual(c.final_all_data_fit_seed,9210000);
assert.strictEqual(c.final_check_trials_per_treatment_path,240);
assert.strictEqual(c.final_check_seed,9610000);
assert.strictEqual(c.physics_dt_s,0.02);
assert.strictEqual(c.common_random_numbers,true);
assert.strictEqual(c.response_rng,'none');
assert.deepStrictEqual(c.estimated_parameters,['sigma_field_mm','kappa_trail_per_s','theta_detect']);
assert.deepStrictEqual(c.parameter_bounds.sigma_field_mm,[2,32]);
assert.deepStrictEqual(c.parameter_bounds.kappa_trail_per_s,[0,16]);
assert.deepStrictEqual(c.parameter_bounds.theta_detect,[0,2]);
assert.deepStrictEqual(c.halton_primes,[2,3,5]);

assert.match(p.execution_trigger_rule,/push to main/i);
assert.match(p.execution_trigger_rule,/no pull_request or workflow_dispatch/i);
assert.match(p.outcome_handling_rule,/closes P4-v1 without rescue or retuning/i);
assert.match(p.rerun_policy,/No rerun is authorized after a valid scientific result/i);
assert.strictEqual(p.P1_official_result_semantic_access_authorized,false);
assert.strictEqual(p.P2_official_result_semantic_access_authorized,false);
assert.strictEqual(p.P3_official_result_semantic_access_authorized,false);
assert.strictEqual(p.P1_P2_P3_rerun_or_refit_authorized,false);
assert.strictEqual(p.canonical_promotion_authorized,false);
assert.strictEqual(p.H2_H3_H4_H5_refit_or_combination_authorized,false);
assert.strictEqual(p.cross_apparatus_validation_authorized,false);
assert.strictEqual(p.ymaze_access_authorized,false);

const w=fs.readFileSync(path.join(root,p.execution_workflow_file),'utf8');
assert.match(w,/branches:\s*\[main\]/);
assert.match(w,/paths:\s*\n\s*- '\.github\/workflows\/p4-v034g-official-highres\.yml'/);
assert.ok(!/workflow_dispatch/.test(w));
assert.ok(!/pull_request/.test(w));
assert.match(w,/cancel-in-progress:\s*false/);
assert.match(w,/test "\$\{GITHUB_REF\}" = "refs\/heads\/main"/);
assert.match(w,/test "\$\{GITHUB_EVENT_NAME\}" = "push"/);
assert.match(w,/node tools\/run-p4-estimation\.js --mode highres --out reports\/p4_response_estimation_2000x60_v1\.json/);
assert.match(w,/\.\/tests\/run-tests\.sh/);
assert.ok(!fs.existsSync(path.join(root,'reports/p4_response_estimation_2000x60_v1.json')));
assert.ok(!fs.existsSync(path.join(root,'reports/p4_response_estimation_execution_provenance_v1.json')));

console.log('p4-highres-execution-precondition.test.js PASS '+JSON.stringify({precondition_blob:blob(rel),workflow_blob:blob(p.execution_workflow_file),main_run:p.permanent_main_workflow.run_id,main_test:p.permanent_main_workflow.test_job_id,main_deploy:p.permanent_main_workflow.deploy_job_id,official_execution_unrun:true,manual_dispatch:false,pull_request_trigger:false,cli_overrides:0,ymaze:false}));
