(() => {
  'use strict';
  const { Simulation, FIXED_DT } = window.AntLabIntegrity;
  const canvas=document.getElementById('labCanvas'),ctx=canvas.getContext('2d');
  const ui={experiment:document.getElementById('experimentSelect'),seed:document.getElementById('seedInput'),speed:document.getElementById('speedSelect'),play:document.getElementById('playBtn'),step:document.getElementById('stepBtn'),reset:document.getElementById('resetBtn'),status:document.getElementById('runStatus'),trails:document.getElementById('showTrails'),ids:document.getElementById('showIds'),contacts:document.getElementById('showContacts'),simTime:document.getElementById('simTime'),meanSpeed:document.getElementById('meanSpeed'),completed:document.getElementById('completedCount'),outcome:document.getElementById('outcomeValue'),straightness:document.getElementById('straightnessValue'),distance:document.getElementById('distanceValue'),truthDistance:document.getElementById('truthDistanceValue'),modelId:document.getElementById('modelId'),modelHash:document.getElementById('modelHash'),stateId:document.getElementById('stateId'),stateHash:document.getElementById('stateHash'),resolvedStateHash:document.getElementById('resolvedStateHash'),apparatusId:document.getElementById('apparatusId'),observationId:document.getElementById('observationId'),scoringId:document.getElementById('scoringId'),experimentHash:document.getElementById('experimentHash'),calibrationRole:document.getElementById('calibrationRole'),protocolNote:document.getElementById('protocolNote'),measurementNote:document.getElementById('measurementNote'),inspectorEmpty:document.getElementById('inspectorEmpty'),inspectorData:document.getElementById('inspectorData'),workerId:document.getElementById('workerId'),workerX:document.getElementById('workerX'),workerY:document.getElementById('workerY'),workerHeading:document.getElementById('workerHeading'),workerState:document.getElementById('workerState'),workerBioState:document.getElementById('workerBioState'),workerOutcome:document.getElementById('workerOutcome')};
  const cache=new Map();let sim=null,running=false,selectedId=null,lastWallTime=performance.now(),simBudget=0;
  async function json(path){if(cache.has(path))return cache.get(path);const r=await fetch(path);if(!r.ok)throw new Error(`Could not load ${path}: HTTP ${r.status}`);const v=await r.json();cache.set(path,v);return v;}
  async function loadBundle(filename){const experiment=await json(`./experiments/${filename}`);const [model,apparatus,state,observation,scoring]=await Promise.all([json(`./models/${experiment.model}.json`),json(`./apparatus/${experiment.apparatus}.json`),json(`./states/${experiment.state}.json`),json(`./observations/${experiment.observation}.json`),json(`./scoring/${experiment.scoring}.json`)]);return{experiment,model,apparatus,state,observation,scoring};}
  async function reset(){running=false;selectedId=null;simBudget=0;ui.play.textContent='Run';ui.status.textContent='LOADING';try{sim=new Simulation(await loadBundle(ui.experiment.value),Number(ui.seed.value)||1);ui.status.textContent='PAUSED';ui.inspectorData.hidden=true;ui.inspectorEmpty.hidden=false;updateDefinition();updateMetrics();draw();}catch(err){console.error(err);ui.status.textContent='LOAD ERROR';ui.protocolNote.textContent=err.message;}}
  function frame(now){const wallDt=Math.min,.05,(now-lastWallTime)/1000);lastWallTime=now;if(running&&sim){simBudget+=wallDt*Number(ui.speed.value);let safety=0;while(simBudget>=FIXED_DT&&safety++<5000){sim.step(FIXED_DT);simBudget-=FIXED_DT;const durationReached=sim.time>=sim.experiment.duration_s&&!sim.allFinished();if(sim.allFinished()||durationReached){if(durationReached)sim.runUntilComplete(0);running=false;ui.play.textContent='Run';ui.status.textContent=durationReached?'DURATION':'COMPLETE';break;}}}if(sim){draw();updateMetrics();updateInspector();}requestAnimationFrame(frame);}
  function transform(){const margin=28,w=sim.apparatus.world.width,h=sim.apparatus.world.height,s=Math.min((canvas.width-margin*2)/w,(canvas.height-margin*2)/h);return{s,ox:(canvas.width-w*s)/2,oy:(canvas.height-h*s)/2};}function toCanvas(x,y){const t=transform();return{x:t.ox+x*t.s,y:t.oy+y*t.s};}
  function drawPrimitive(p,fill,stroke){const t=transform();ctx.save();ctx.fillStyle=fill;ctx.strokeStyle=stroke;ctx.lineWidth=1.2;if(p.type==='rect'){ctx.beginPath();ctx.rect(t.ox+p.x*t.s,t.oy+p.y*t.s,p.width*t.s,p.height*t.s);ctx.fill();ctx.stroke();}else if(p.type==='circle'){const c=toCanvas(p.x,p.y);ctx.beginPath();ctx.arc(c.x,c.y,p.radius*t.s,0,Math.PI*2);ctx.fill();ctx.stroke();}else if(p.type==='corridor'){const a=toCanvas(p.x1,p.y1),b=toCanvas(p.x2,p.y2);ctx.lineCap='round';ctx.lineWidth=p.width*t.s;ctx.strokeStyle=fill;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.lineWidth=1.2;ctx.strokeStyle=stroke;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}ctx.restore();}
  function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#090b0d';ctx.fillRect(0,0,canvas.width,canvas.height);for(const p of sim.apparatus.geometry.primitives)drawPrimitive(p,'rgba(148,163,184,.10)','rgba(255,255,255,.18)');for(const r of sim.scoringProfile.regions||[])drawPrimitive(r.shape||r,'rgba(96,165,250,.15)','rgba(96,165,250,.60)');const e=sim.compiled.entry,c=toCanvas(e.x,e.y);ctx.strokeStyle='rgba(217,249,157,.5)';ctx.beginPath();ctx.arc(c.x,c.y,7,0,Math.PI*2);ctx.stroke();if(ui.trails.checked)for(const ant of sim.ants){if(ant.tail.length<2)continue;ctx.strokeStyle='rgba(217,249,157,.12)';ctx.lineWidth=1;ctx.beginPath();ant.tail.forEach((p,i)=>{const q=toCanvas(p.x,p.y);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y)});ctx.stroke();}for(const ant of sim.ants)drawAnt(ant);}
  function drawAnt(ant){const c=toCanvas(ant.x,ant.y),size=3.2;ctx.save();ctx.translate(c.x,c.y);ctx.rotate(ant.heading);ctx.fillStyle=ant.id===selectedId?'#d9f99d':ant.finished?'#60a5fa':'#f5f5f4';ctx.beginPath();ctx.ellipse(0,0,size*1.55,size,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(size*1.7,0,size*.62,0,Math.PI*2);ctx.fill();if(ui.contacts.checked&&ant.contactFlash>0){ctx.strokeStyle='rgba(251,113,133,.9)';ctx.beginPath();ctx.arc(0,0,7,0,Math.PI*2);ctx.stroke();}ctx.restore();if(ui.ids.checked){ctx.fillStyle='rgba(255,255,255,.55)';ctx.font='10px ui-monospace';ctx.fillText(String(ant.id),c.x+5,c.y-5);}}
  function updateDefinition(){ui.modelId.textContent=sim.model.id;ui.modelHash.textContent=sim.layerHashes.model_hash;ui.stateId.textContent=sim.stateProfile.id;ui.stateHash.textContent=sim.layerHashes.state_profile_hash;ui.resolvedStateHash.textContent=sim.layerHashes.resolved_state_hash;ui.apparatusId.textContent=sim.integrity.apparatus.id;ui.observationId.textContent=sim.observationProfile.id;ui.scoringId.textContent=sim.scoringProfile.id;ui.experimentHash.textContent=sim.layerHashes.experiment_hash;ui.calibrationRole.textContent=sim.experiment.calibration_role;const p=sim.experiment.protocol;ui.protocolNote.textContent=`${sim.experiment.title}. Approach: ${p.approach_distance_mm??'n/a'} mm. Treatment: ${p.treatment?.type||'none'}. Observation: ${sim.observationProfile.fps} fps. Scoring: ${sim.scoringProfile.type}.`;}
  function updateMetrics(){const s=sim.summary(),om=s.observed_metrics?.means||{},truth=s.truth_metrics||{};ui.simTime.textContent=`${sim.time.toFixed(1)} s`;ui.meanSpeed.textContent=Number.isFinite(om.mean_moving_speed_mm_s)?`${om.mean_moving_speed_mm_s.toFixed(1)} mm/s`:'—';ui.completed.textContent=`${s.completed}/${s.workers}`;const outcomes=Object.entries(s.outcomes||{}).filter(([,n])=>n>0);ui.outcome.textContent=outcomes.length?outcomes.map(([name,n])=>`${name.toUpperCase()}${n>1?` ×${n}`:''}`).join(', '):'—';ui.straightness.textContent=Number.isFinite(om.path_straightness)?om.path_straightness.toFixed(3):'—';ui.distance.textContent=Number.isFinite(om.total_distance_mm)?`${om.total_distance_mm.toFixed(1)} mm`:'—';ui.truthDistance.textContent=Number.isFinite(truth.mean_distance_mm)?`${truth.mean_distance_mm.toFixed(1)} mm`:'—';const observed=s.observed_metrics,status=observed?.measurement_status;ui.measurementNote.textContent=status?`Measured from ${observed.fps} fps observations. Movement classifier: ${status.movement_classifier?.status||'unspecified'}. Truth metrics are kept separate.`:'';}
  function updateInspector(){if(selectedId==null||!sim)return;const a=sim.ants.find(x=>x.id===selectedId);if(!a)return;ui.workerId.textContent=`#${a.id}`;ui.workerX.textContent=`${a.x.toFixed(2)} mm`;ui.workerY.textContent=`${a.y.toFixed(2)} mm`;ui.workerHeading.textContent=`${((((a.heading*180/Math.PI)%360)+360)%360).toFixed(1)}°`;ui.workerState.textContent=a.state;ui.workerBioState.textContent=a.agentState?`${a.agentState.experience}; ${a.agentState.travel_direction}; ${a.agentState.feeding_state}; recent travel ${a.agentState.recent_travel_mm} mm`:'—';ui.workerOutcome.textContent=a.outcome||'—';}
  canvas.addEventListener('click',e=>{if(!sim)return;const r=canvas.getBoundingClientRect(),mx=(e.clientX-r.left)/r.width*canvas.width,my=(e.clientY-r.top)/r.height*canvas.height;let best=null,bestD=Infinity;for(const a of sim.ants){const c=toCanvas(a.x,a.y),d=(c.x-mx)**2+(c.y-my)**2;if(d<bestD){bestD=d;best=a;}}if(best&&bestD<18**2){selectedId=best.id;ui.inspectorEmpty.hidden=true;ui.inspectorData.hidden=false;updateInspector();}});
  ui.play.addEventListener('click',()=>{if(!sim)return;running=!running;ui.play.textContent=running?'Pause':'Run';ui.status.textContent=running?'RUNNING':'PAUSED';});ui.reset.addEventListener('click',reset);ui.step.addEventListener('click',()=>{if(!sim)return;running=false;ui.play.textContent='Run';sim.runFor(1,FIXED_DT);updateMetrics();draw();});ui.seed.addEventListener('change',reset);ui.experiment.addEventListener('change',reset);reset();requestAnimationFrame(frame);
})();
