(function (root, factory) {
  const core = (typeof module === 'object' && module.exports) ? require('./sim-core.js') : root.AntLabCore;
  const api = factory(core);
  if (typeof module === 'object' && module.exports) module.exports = api;
  root.AntLabMeasurement = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function (core) {
  'use strict';
  if (!core) throw new Error('ANTLAB measurement layer requires AntLabCore');
  const EPS=1e-9;
  function clone(v){return JSON.parse(JSON.stringify(v));}function clamp(v,lo,hi){return Math.max(lo,Math.min(hi,v));}
  function snapshotAnts(ants){return ants.map(a=>({id:a.id,x:a.x,y:a.y,heading:a.heading,state:a.state,outcome:a.outcome,finished:a.finished,completedAt:a.completedAt}));}
  function interpolateAngle(a,b,alpha){return core.normalizeAngle(a+core.normalizeAngle(b-a)*alpha);}
  function interpolateFrame(before,after,t0,t1,sampleTime,observation,rng){const byId=new Map(before.map(a=>[a.id,a])),noiseSd=Number(observation?.tracking?.position_noise_mm_sd)||0;const ants=after.map(a=>{const b=byId.get(a.id)||a,hasSubstepEnd=a.finished&&a.completedAt!=null&&a.completedAt<t1-EPS,effectiveEnd=hasSubstepEnd?Math.max(t0,a.completedAt):t1,terminal=a.finished&&a.completedAt!=null&&sampleTime+EPS>=a.completedAt,span=Math.max(EPS,effectiveEnd-t0),alpha=terminal?1:clamp((sampleTime-t0)/span,0,1);let x=b.x+(a.x-b.x)*alpha,y=b.y+(a.y-b.y)*alpha;if(noiseSd>0&&rng){x+=rng.normal()*noiseSd;y+=rng.normal()*noiseSd;}return{id:a.id,x,y,heading:terminal?a.heading:interpolateAngle(b.heading,a.heading,alpha),state:terminal?'finished':(alpha<.5?b.state:a.state),outcome:terminal?a.outcome:null};});return{time_s:Number(sampleTime.toFixed(9)),ants};}
  function currentFrame(ants,sampleTime,observation,rng){const noiseSd=Number(observation?.tracking?.position_noise_mm_sd)||0;return{time_s:Number(sampleTime.toFixed(9)),ants:ants.map(a=>{let x=a.x,y=a.y;if(noiseSd>0&&rng){x+=rng.normal()*noiseSd;y+=rng.normal()*noiseSd;}return{id:a.id,x,y,heading:a.heading,state:a.state,outcome:a.outcome};})};}
  function classifierConfig(observation){const raw=observation?.tracking?.movement_classifier;if(!raw||typeof raw==='string')return{type:'nonzero_displacement',threshold_mm:0,status:observation?.tracking?.status||'unspecified'};return Object.assign({type:'nonzero_displacement',threshold_mm:0,status:'unspecified'},raw);}
  function isMoving(d,dt,c){if(!(dt>0))return false;if(c.type==='frame_displacement_threshold')return d>Number(c.threshold_mm||0)+EPS;if(c.type==='speed_threshold')return d/dt>Number(c.threshold_mm_s||0)+EPS;return d>EPS;}
  function inZone(x,y,d){if(!d)return false;if(d.type==='horizontal_band')return Math.abs(y-Number(d.center_y_mm))<=Number(d.half_width_mm)+EPS;if(d.type==='vertical_band')return Math.abs(x-Number(d.center_x_mm))<=Number(d.half_width_mm)+EPS;if(d.type==='rect')return x>=d.x&&x<=d.x+d.width&&y>=d.y&&y<=d.y+d.height;return false;}
  class MeasurementPipeline{
    constructor(observation,experiment,apparatus){this.observation=clone(observation||{});this.experiment=clone(experiment||{});this.apparatus=clone(apparatus||{});this.requested=Array.from(new Set(this.experiment.requested_metrics||this.observation.default_metrics||[]));this.classifier=classifierConfig(this.observation);this.centralZone=this.observation.metric_definitions?.central_zone_fraction||null;this.perAnt=new Map();this.frameCount=0;}
    observe(frame){this.frameCount++;for(const ant of frame.ants){let m=this.perAnt.get(ant.id);if(!m){m={first:{x:ant.x,y:ant.y,time_s:frame.time_s},prev:{x:ant.x,y:ant.y,time_s:frame.time_s},last:{x:ant.x,y:ant.y,time_s:frame.time_s},totalDistance:0,movingDistance:0,movingTime:0,observedDuration:0,zoneSamples:this.centralZone&&inZone(ant.x,ant.y,this.centralZone)?1:0,outcome:ant.outcome||null,outcomeTime:ant.outcome?frame.time_s:null,exitX:ant.outcome?ant.x:null,exitY:ant.outcome?ant.y:null,samples:1};this.perAnt.set(ant.id,m);continue;}if(m.outcome)continue;const dt=frame.time_s-m.prev.time_s;if(dt>EPS){const d=Math.hypot(ant.x-m.prev.x,ant.y-m.prev.y);m.totalDistance+=d;m.observedDuration+=dt;if(isMoving(d,dt,this.classifier)){m.movingDistance+=d;m.movingTime+=dt;}}if(this.centralZone&&inZone(ant.x,ant.y,this.centralZone))m.zoneSamples++;m.prev={x:ant.x,y:ant.y,time_s:frame.time_s};m.last={x:ant.x,y:ant.y,time_s:frame.time_s};m.samples++;if(ant.outcome){m.outcome=ant.outcome;m.outcomeTime=frame.time_s;m.exitX=ant.x;m.exitY=ant.y;}}}
    finalize(ants){const interval=1/Math.max(.1,Number(this.observation.fps)||25);for(const ant of ants){const m=this.perAnt.get(ant.id);if(!m||m.outcome||!ant.finished)continue;const eventTime=Number(ant.completedAt),observedTime=Math.ceil(Math.max(0,eventTime-EPS)/interval)*interval;m.outcome=ant.outcome;m.outcomeTime=Number(observedTime.toFixed(9));m.exitX=ant.exitX==null?ant.x:ant.exitX;m.exitY=ant.exitY==null?ant.y:ant.exitY;const dt=m.outcomeTime-m.prev.time_s;if(dt>EPS){const d=Math.hypot(m.exitX-m.prev.x,m.exitY-m.prev.y);m.totalDistance+=d;m.observedDuration+=dt;if(isMoving(d,dt,this.classifier)){m.movingDistance+=d;m.movingTime+=dt;}}if(this.centralZone&&inZone(m.exitX,m.exitY,this.centralZone))m.zoneSamples++;m.prev={x:m.exitX,y:m.exitY,time_s:m.outcomeTime};m.last={x:m.exitX,y:m.exitY,time_s:m.outcomeTime};m.samples++;m.syntheticTerminalFrame=true;}}
    metricRow(id){const m=this.perAnt.get(id);if(!m)return null;const fps=Number(this.observation.fps)||25,beeline=Math.hypot(m.last.x-m.first.x,m.last.y-m.first.y),row={ant_id:id,samples:m.samples,total_frames:m.samples,outcome:m.outcome,measurement_status:{fps,movement_classifier:clone(this.classifier),terminal_frame_synthesized:!!m.syntheticTerminalFrame},all_tracked_distance_mm:m.totalDistance,observed_outcome_frame_time_s:m.outcomeTime};if(this.requested.includes('central_zone_fraction'))row.central_zone_fraction=m.samples>0?m.zoneSamples/m.samples:0;if(this.requested.includes('mean_moving_speed'))row.mean_moving_speed_mm_s=m.movingTime>0?m.movingDistance/m.movingTime:0;if(this.requested.includes('total_distance'))row.total_distance_mm=m.movingDistance;if(this.requested.includes('time_to_arena_edge'))row.time_to_arena_edge_s=m.outcome?m.samples/fps:null;if(this.requested.includes('path_straightness'))row.path_straightness=m.movingDistance>0?beeline/m.movingDistance:0;if(this.requested.includes('exit_coordinate'))row.exit_coordinate_mm=m.exitX==null?null:{x:m.exitX,y:m.exitY};if(this.requested.includes('branch_choice'))row.branch_choice=m.outcome;return row;}
    summary(ants){this.finalize(ants);const fps=Number(this.observation.fps)||25,rows=ants.map(a=>this.metricRow(a.id)).filter(Boolean),mean=key=>{const vals=rows.map(r=>r[key]).filter(v=>Number.isFinite(v));return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null;};return{observation_id:this.observation.id,fps,frame_count:this.frameCount,requested_metrics:clone(this.requested),measurement_status:{fps,tracking_status:this.observation.tracking?.status||'unspecified',movement_classifier:clone(this.classifier),source:'observed_trajectory',distance_definition:'moving-only displacement (Traveled_Dist_Moving)',straightness_definition:'beeline / moving-only distance',time_to_edge_definition:'Total_Frames / fps'},means:{central_zone_fraction:mean('central_zone_fraction'),mean_moving_speed_mm_s:mean('mean_moving_speed_mm_s'),total_distance_mm:mean('total_distance_mm'),time_to_arena_edge_s:mean('time_to_arena_edge_s'),path_straightness:mean('path_straightness')},ants:rows};}
  }
  return{snapshotAnts,interpolateFrame,currentFrame,MeasurementPipeline,classifierConfig,inZone};
});
